"""Add PostgreSQL compatibility and timezone support

Revision ID: b247d7245896
Revises: ba77ed883ca0
Create Date: 2026-04-12 20:39:52.697598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b247d7245896'
down_revision: Union[str, Sequence[str], None] = 'ba77ed883ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration ensures PostgreSQL compatibility
    # No schema changes needed - just placeholder for PostgreSQL-specific configs
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
