"""Initial baseline - create all tables for Fase 1

Revision ID: ba77ed883ca0
Revises: 
Create Date: 2026-04-12 20:39:46.546514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba77ed883ca0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_organization_id'), 'events', ['organization_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_membership_user_org')
    )
    op.create_index(op.f('ix_memberships_organization_id'), 'memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('draw_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('draw_config_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'draw_config_id', name='uq_draw_event_cfg')
    )
    op.create_index(op.f('ix_draw_configs_event_id'), 'draw_configs', ['event_id'], unique=False)
    op.create_table('draw_registration_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('draw_config_id', sa.String(length=64), nullable=False),
    sa.Column('public_token', sa.String(length=64), nullable=False),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('join_base_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draw_registration_sessions_draw_config_id'), 'draw_registration_sessions', ['draw_config_id'], unique=False)
    op.create_index(op.f('ix_draw_registration_sessions_event_id'), 'draw_registration_sessions', ['event_id'], unique=False)
    op.create_index(op.f('ix_draw_registration_sessions_public_token'), 'draw_registration_sessions', ['public_token'], unique=True)
    op.create_table('export_packages',
    sa.Column('export_id', sa.String(length=80), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('export_directory', sa.Text(), nullable=False),
    sa.Column('zip_path', sa.Text(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('export_id')
    )
    op.create_index(op.f('ix_export_packages_event_id'), 'export_packages', ['event_id'], unique=False)
    op.create_table('media_requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('media_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'media_id', name='uq_media_event_media')
    )
    op.create_index(op.f('ix_media_requirements_event_id'), 'media_requirements', ['event_id'], unique=False)
    op.create_table('scenes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('scene_id', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'scene_id', name='uq_scenes_event_scene')
    )
    op.create_index(op.f('ix_scenes_event_id'), 'scenes', ['event_id'], unique=False)
    op.create_table('draw_registrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('assigned_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['draw_registration_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draw_registrations_session_id'), 'draw_registrations', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_draw_registrations_session_id'), table_name='draw_registrations')
    op.drop_table('draw_registrations')
    op.drop_index(op.f('ix_scenes_event_id'), table_name='scenes')
    op.drop_table('scenes')
    op.drop_index(op.f('ix_media_requirements_event_id'), table_name='media_requirements')
    op.drop_table('media_requirements')
    op.drop_index(op.f('ix_export_packages_event_id'), table_name='export_packages')
    op.drop_table('export_packages')
    op.drop_index(op.f('ix_draw_registration_sessions_public_token'), table_name='draw_registration_sessions')
    op.drop_index(op.f('ix_draw_registration_sessions_event_id'), table_name='draw_registration_sessions')
    op.drop_index(op.f('ix_draw_registration_sessions_draw_config_id'), table_name='draw_registration_sessions')
    op.drop_table('draw_registration_sessions')
    op.drop_index(op.f('ix_draw_configs_event_id'), table_name='draw_configs')
    op.drop_table('draw_configs')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_organization_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_events_organization_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
